export interface Storybook {
  objectId: string | null; // use storybook_id instead of objectId. objectId is autogenerated meaningless id from Back4App
  index: number;
  storybook_id: string;
  admin_id: number;
  created_by: CreatedBy[] | null;
  storybook_title: string;
  storybook_description: string | null;
  cover_image_url: string;
  paid_storybook: boolean;
  language: string | null;
  genre: string[] | null;
  published: string | null;
  published_in: string | null;
  publisher: string | null;
  ISBN: string | null;
  contributed_by: string | null;
  storybook_image_url: string[];
}

export type CreatedBy = {
  role: string;
  name: string;
}